version: '3.4'

services:
  influxdb:
    image: influxdb:1.7.1-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - architectchallenge
    environment:
      INFLUXDB_DB: appmetrics
      INFLUXDB_USER: influxUser
      INFLUXDB_USER_PASSWORD: influxPwd

  grafana:
    image: grafana/grafana:5.4.0    
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - architectchallenge

networks:
  architectchallenge:
    driver: bridge
